let name = "Vegeta";
let jumpforce = 20000; 
let specialPower = "teleport"; 
let speed = 3890; 
let bike = "Honda VFR VTEC"; 
let livesLeft = 11; 
let ammo = 121; 
let numberOfLasers = 50; 
let batteryPower = 9000; 
let level = 9000; 
let wanted = true; 

console.log("name: " + name);
console.log("jumpforce: " + jumpforce);
console.log("special power: " + specialPower);
console.log("speed: " + speed);
console.log("bike: " + bike);
console.log("lives left: " + livesLeft);
console.log("ammo: " + ammo);
console.log("number of lasers: " + numberOfLasers);
console.log("battery power: " + batteryPower);
console.log("level: " + level);
console.log("wanted: " + wanted);